server:
  port: 8638
spring:
  application:
    name: feign-consumer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8633/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
