
server:
  port: 8081

spring:
  application:
    name: hello-service

eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer34:8634/eureka/,http://eurekaServer33:8633/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}