server:
  port: 8637

spring:
  application:
    name: Ribbon-Hystrix-Consumer

providers:
  ribbion:
    listOfServers: localhost:8634,localhost:8635


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8633/eureka/


NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule