server:
  port: 8636

spring:
  application:
    name: Ribbon-Consumer

providers:
  ribbion:
    listOfServers: localhost:8634,localhost:8635


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8633/eureka/
